cd ~/Documents/MTECH/Exercises
git clone git@github.com:ChrisGuenther333/Day2Exercise.git
cd Day2Exercise
touch index.html
mkdir css
cd css
touch style.css
cd ..
mkdir pages
cd pages
mkdir about
cd about
touch about.html
touch about.css
cd ..
mkdir contact
cd contact
touch contact.html
touch contact.css
cd ..
mkdir images
cd images
touch companyLogo.png
mkdir icons
cd icons
touch email.png
touch phone.png
touch chat.png
cd ../..
mkdir js
cd js
touch index.js